from PyQt5.QtGui import QFont
from PyQt5.QtCore import Qt, QRect
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QPushButton
class EndScreen(QWidget):
    
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setObjectName("EndScreen")
        self.resize(1200, 960)

        self.dark_background = QLabel(self)
        self.dark_background.setGeometry(QRect(0, 0, 1200, 960))
        self.dark_background.setAutoFillBackground(False)
        self.dark_background.setStyleSheet("background-color: rgba(0, 0, 0, 180);")
        self.dark_background.setText("")
        self.dark_background.setObjectName("dark_background")

    def setupDefeat(self):

        self.design_stripe = QLabel(self)
        self.design_stripe.setGeometry(QRect(0, 240, 1200, 480))
        self.design_stripe.setAutoFillBackground(False)
        self.design_stripe.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.505273, y1:0.506, x2:0.5, y2:1, stop:0.630682 rgba(255, 0, 0, 244), stop:1 rgba(255, 255, 255, 0));")
        self.design_stripe.setText("")
        self.design_stripe.setObjectName("design_stripe")

        self.defeat_label = QLabel(self)
        self.defeat_label.setGeometry(QRect(420, 140, 360, 140))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.defeat_label.setFont(font)
        self.defeat_label.setStyleSheet("color: rgb(214, 0, 0);")
        self.defeat_label.setTextFormat(Qt.PlainText)
        self.defeat_label.setScaledContents(False)
        self.defeat_label.setAlignment(Qt.AlignCenter)
        self.defeat_label.setObjectName("defeat_label")
        self.defeat_label.setText("Defeat")

        self.kills_label = QLabel(self)
        self.kills_label.setGeometry(QRect(250, 350, 140, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.kills_label.setFont(font)
        self.kills_label.setObjectName("kills_label")
        self.kills_label.setText("Kills:")

        self.kills_score = QLabel(self)
        self.kills_score.setGeometry(QRect(710, 350, 200, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.kills_score.setFont(font)
        self.kills_score.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.kills_score.setObjectName("kills_score")
        self.kills_score.setText("0")

        self.time_label = QLabel(self)
        self.time_label.setGeometry(QRect(250, 420, 320, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.time_label.setText("Time survived:")

        self.time_score = QLabel(self)
        self.time_score.setGeometry(QRect(710, 420, 200, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.time_score.setFont(font)
        self.time_score.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.time_score.setObjectName("time_score")
        self.time_score.setText("0")

        self.points_label = QLabel(self)
        self.points_label.setGeometry(QRect(250, 490, 160, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.points_label.setFont(font)
        self.points_label.setObjectName("points_label")
        self.points_label.setText("Points:")

        self.points_score = QLabel(self)
        self.points_score.setGeometry(QRect(710, 490, 200, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.points_score.setFont(font)
        self.points_score.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.points_score.setObjectName("points_score")
        self.points_score.setText("0")

        self.retry_button = QPushButton(self)
        self.retry_button.setGeometry(QRect(680, 620, 180, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.retry_button.setFont(font)
        self.retry_button.setStyleSheet("background-color: rgb(62, 62, 62);\n"
										"color: rgb(243, 0, 0);")
        self.retry_button.setObjectName("retry_button")
        self.retry_button.setText("Retry")

        self.quit_button = QPushButton(self)
        self.quit_button.setGeometry(QRect(340, 620, 180, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("background-color: rgb(62, 62, 62);\n"
									   "color: rgb(243, 0, 0);")
        self.quit_button.setObjectName("quit_button")
        self.quit_button.setText("Quit")
        
    def setupVictory(self, kills, time, points):

        self.design_stripe = QLabel(self)
        self.design_stripe.setGeometry(QRect(0, 240, 1200, 480))
        self.design_stripe.setAutoFillBackground(False)
        self.design_stripe.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0.505273, y1:0.506, x2:0.5, y2:1, stop:0.630682 rgba(0, 55, 255, 244), stop:1 rgba(255, 255, 255, 0));")
        self.design_stripe.setText("")
        self.design_stripe.setObjectName("design_stripe")

        self.victory_label = QLabel(self)
        self.victory_label.setGeometry(QRect(390, 140, 420, 140))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.victory_label.setFont(font)
        self.victory_label.setStyleSheet("color: rgb(250, 203, 17);")
        self.victory_label.setTextFormat(Qt.PlainText)
        self.victory_label.setScaledContents(False)
        self.victory_label.setAlignment(Qt.AlignCenter)
        self.victory_label.setObjectName("victory_label")
        self.victory_label.setText("Victory")

        self.kills_label = QLabel(self)
        self.kills_label.setGeometry(QRect(250, 350, 140, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.kills_label.setFont(font)
        self.kills_label.setStyleSheet("color: rgb(250, 203, 17);")
        self.kills_label.setObjectName("kills_label")
        self.kills_label.setText("Kills:")

        self.kills_score = QLabel(self)
        self.kills_score.setGeometry(QRect(710, 350, 200, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.kills_score.setFont(font)
        self.kills_score.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.kills_score.setStyleSheet("color: rgb(250, 203, 17);")
        self.kills_score.setObjectName("kills_score")
        self.kills_score.setText(kills.__str__())

        self.time_label = QLabel(self)
        self.time_label.setGeometry(QRect(250, 420, 320, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color: rgb(250, 203, 17);")
        self.time_label.setObjectName("time_label")
        self.time_label.setText("Time survived:")

        self.time_score = QLabel(self)
        self.time_score.setGeometry(QRect(710, 420, 200, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.time_score.setFont(font)
        self.time_score.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.time_score.setStyleSheet("color: rgb(250, 203, 17);")
        self.time_score.setObjectName("time_score")
        self.time_score.setText(time.__str__())

        self.points_label = QLabel(self)
        self.points_label.setGeometry(QRect(250, 490, 160, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.points_label.setFont(font)
        self.points_label.setStyleSheet("color: rgb(250, 203, 17);")
        self.points_label.setObjectName("points_label")
        self.points_label.setText("Points:")

        self.points_score = QLabel(self)
        self.points_score.setGeometry(QRect(710, 490, 200, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.points_score.setFont(font)
        self.points_score.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.points_score.setStyleSheet("color: rgb(250, 203, 17);")
        self.points_score.setObjectName("points_score")
        self.points_score.setText(points.__str__())

        self.retry_button = QPushButton(self)
        self.retry_button.setGeometry(QRect(680, 620, 180, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.retry_button.setFont(font)
        self.retry_button.setStyleSheet("background-color: rgb(18, 16, 156);\n"
										"color: rgb(250, 203, 17);")
        self.retry_button.setObjectName("retry_button")
        self.retry_button.setText("Replay")

        self.quit_button = QPushButton(self)
        self.quit_button.setGeometry(QRect(340, 620, 180, 60))
        font = QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(28)
        self.quit_button.setFont(font)
        self.quit_button.setStyleSheet("background-color: rgb(18, 16, 156);\n"
									   "color: rgb(250, 203, 17);")
        self.quit_button.setObjectName("quit_button")
        self.quit_button.setText("Quit")

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    widget = EndScreen()
    widget.setupVictory(10, 10, 1000)
    widget.show()
    sys.exit(app.exec_())